apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-username: bXlzcWx1c2Vy # base64 encoded 'mysqluser'
  mysql-password: bXlzcWxwYXNz # base64 encoded 'mysqlpass'
